# Generated by Django 3.2 on 2021-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='member_address',
        ),
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='members',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='email_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
