# Generated by Django 3.2 on 2021-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0002_auto_20210525_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email_address',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
