# Generated by Django 3.2 on 2021-05-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0003_alter_members_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_rental',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videostore.members', verbose_name='Member Name'),
        ),
        migrations.AlterField(
            model_name='movie_rental',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videostore.movies', verbose_name='Movie Name'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
