# Generated by Django 3.2 on 2021-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0004_auto_20210525_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Age'),
        ),
    ]
