# Generated by Django 3.2 on 2021-05-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0005_alter_members_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
