# Generated by Django 3.2 on 2021-05-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videostore', '0006_alter_members_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
